[package]
name = "gameboy-core"
version = "0.1.0"
edition = "2021"

[features]
default = []
audio = ["blip_buf"]
inspect = []

[dependencies]
blip_buf = { version = "0.1", optional = true }
thiserror = "1.0"
